//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bid
    {
        public int B_ID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> PropertyID { get; set; }
    
        public virtual tbl_Property tbl_Property { get; set; }
    }
}
